[package]
name = "extended-array"
version = "0.1.0"
authors = ["ilian98 <ilian2105@abv.bg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
reqwest = { version = "0.11.0", features = ["blocking"] }